/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcureToPayRouteImport } from './routes/procure-to-pay'
import { Route as IndexRouteImport } from './routes/index'

const ProcureToPayRoute = ProcureToPayRouteImport.update({
  id: '/procure-to-pay',
  path: '/procure-to-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/procure-to-pay': typeof ProcureToPayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/procure-to-pay': typeof ProcureToPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/procure-to-pay': typeof ProcureToPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/procure-to-pay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/procure-to-pay'
  id: '__root__' | '/' | '/procure-to-pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProcureToPayRoute: typeof ProcureToPayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procure-to-pay': {
      id: '/procure-to-pay'
      path: '/procure-to-pay'
      fullPath: '/procure-to-pay'
      preLoaderRoute: typeof ProcureToPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProcureToPayRoute: ProcureToPayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
